language: ruby
rvm:
  - 2.3.1
dist: trusty
addons:
  postgresql: 9.3
  apt:
    packages:
    - gifsicle
    - jpegoptim
    - optipng
    - jhead
before_install:
  - git clone https://github.com/discourse/discourse.git
install:
  - cd discourse
  - bundle install --without development --deployment
before_script:
  - cd discourse
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rspec
