language: ruby
dist: trusty
rvm:
  - 2.3.1
before_install:
  - git clone https://github.com/discourse/discourse.git
  - puts ls -la
install:
  - bundle install --without development --deployment
before_script:
  - bundle exec rake -T
  - bundle exec rake db:create db:migrate
