language: ruby
rvm:
  - 2.3.1
dist: trusty
addons:
  postgresql: 9.3
  apt:
    packages:
    - gifsicle
    - jpegoptim
    - optipng
before_install:
  - cd ~ && git clone https://github.com/discourse/discourse.git
  - pwd
  - ls -l
install:
  - rm ~/discourse/README.md
  - cp -R ~/discourse/* .
  - ls -l
  - bundle install --without development --deployment
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rspec
